### ISSUE TITLE
forms need to be thoroughly checked again

### ISSUE THREAD

**Issue by LinguList** [lexibank/transnewguineaorg#12]
@tresoldi, if you check teh forms thoroughly, you will see that there are many which say "-verb" or "give", etc. These are treated as if they were sound sequences now. This needs a very careful checking.

**Comment by tresoldi** [comment]
There indeed, but I think it would be better to correct these cases with code than with the profile (or perhaps using `lexemes.csv`? Or FormSpec replacements?). Back when I did the profile, @SimonGreenhill had mentioned that errors should be fixed in TNG itself, but I agree it is better to remove them here if it is easy enough. Any preference? (both @LinguList and @SimonGreenhill )

**Comment by SimonGreenhill** [comment]
@LinguList  -- does this catch the errors? https://github.com/lexibank/transnewguineaorg/commit/2c0431008d915315d32667fbc787ecf68e066412

**Comment by LinguList** [comment]
Most of it, as far as I can say. I used a rather extreme mix of lexemes
/ replacements / and orthography profile, and could not spot any more
examples for now. I also corrected many decisions in the orthoprofile,
which are less favorable for automated comparison.

**Comment by SimonGreenhill** [comment]
Awesome, thanks for looking into this @LinguList !
